name: Rate Joke
run-name: Rate Joke by ${{ github.event.comment.user.login }}

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read
  models: read

jobs:
  joke:
    name: Rate Joke
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rate Joke
        id: rate-joke
        uses: ./
        with:
          joke: ${{ github.event.comment.body }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment
        if: fromJSON(steps.rate-joke.outputs.result).is_joke == true
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ fromJSON(steps.rate-joke.outputs.result).rating }}
